web_server:
  bind: 0.0.0.0
  port: 5050

webui:
  password: Raspberry

schedules:
  - tasks: '*'
    interval:
      minutes: 10

tasks:
  move_media_files:
    priority: 1
    no_entries_ok: yes
    filesystem:
      path: /downloads/
      regexp: '.*\.(avi|mkv|mp4)$'
      recursive: yes
    accept_all: yes
    exec:
      auto_escape: yes
      on_output:
        for_entries: >
          if echo "{{ location }}" | grep -i -E 'S[0-9]{2}E[0-9]{2}'; then
            mkdir -p "/storage/series" && mv "{{ location }}" "/storage/series/"
          else
            mkdir -p "/storage/pelis" && mv "{{ location }}" "/storage/pelis/"
          fi

  remove_finished_torrents:
    from_transmission:
      host: transmission
      port: 9091
      username: pi
      password: Raspberry
    disable:
      - seen
      - seen_info_hash
    if:
      - transmission_progress == 100: accept
    transmission:
      host: transmission
      port: 9091
      username: pi
      password: Raspberry
      action: remove
